# Generated by Django 4.1.7 on 2023-03-24 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('idBUS', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('num_bus', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('climatizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idRUTA', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUSUARIOS', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idVIAJE', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=45)),
                ('destino', models.CharField(max_length=45)),
                ('fecha_hora', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clase', models.CharField(max_length=45)),
                ('cupo', models.IntegerField()),
                ('fk_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.bus')),
                ('fk_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEMPRESA', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fk_gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='fk_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_transporte.empresa'),
        ),
    ]
